-- ============================================
-- Block Ops — Pilot seed for content objects
-- Seeds Foundation deliverables + current agent knowledge
-- Run after content-objects-setup.sql
-- ============================================

begin;

-- 1. Seed canonical objects
insert into content_objects (object_id, title, slug, object_type, package, owner) values
  ('foundation.adjuvant-dosing-guide', 'Adjuvant Dosing Guide', 'adjuvant-dosing-guide', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.block-bay-workflow-logic', 'Block Bay Workflow Logic', 'block-bay-workflow-logic', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.block-cart-par-level-guide', 'Block Cart Par Level Guide', 'block-cart-par-level-guide', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.block-cart-planogram', 'Block Cart Planogram', 'block-cart-planogram', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.block-champion-charter', 'Block Champion Charter', 'block-champion-charter', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.block-lead-nurse-responsibility-list', 'Block Lead Nurse Responsibility List', 'block-lead-nurse-responsibility-list', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.block-procedure-note-template', 'Block Procedure Note Template', 'block-procedure-note-template', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.block-status-tracking-board-guide', 'Block Status Tracking Board Guide', 'block-status-tracking-board-guide', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.block-success-failure-log', 'Block Success Failure Log', 'block-success-failure-log', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.block-time-out-checklist', 'Block Time Out Checklist', 'block-time-out-checklist', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.breakthrough-pain-protocol', 'Breakthrough Pain Protocol', 'breakthrough-pain-protocol', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.clean-vs-sterile-protocol', 'Clean vs Sterile Protocol', 'clean-vs-sterile-protocol', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.cpt-icd10-crosswalk', 'CPT ICD10 Crosswalk', 'cpt-icd10-crosswalk', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.daily-cart-restock-checklist', 'Daily Cart Restock Checklist', 'daily-cart-restock-checklist', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.exparel-utilization-criteria', 'Exparel Utilization Criteria', 'exparel-utilization-criteria', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.fall-prevention-patient-agreement', 'Fall Prevention Patient Agreement', 'fall-prevention-patient-agreement', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.fall-risk-assessment', 'Fall Risk Assessment', 'fall-risk-assessment', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.gel-management-sop', 'Gel Management SOP', 'gel-management-sop', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.high-volume-dilution-chart', 'High Volume Dilution Chart', 'high-volume-dilution-chart', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.hydrodissection-opening-pressure-protocol', 'Hydrodissection Opening Pressure Protocol', 'hydrodissection-opening-pressure-protocol', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.in-plane-technique-sop', 'In Plane Technique SOP', 'in-plane-technique-sop', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.intraneural-injection-stop-criteria', 'Intraneural Injection Stop Criteria', 'intraneural-injection-stop-criteria', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.knobology-cheat-sheet', 'Knobology Cheat Sheet', 'knobology-cheat-sheet', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.la-selection-algorithm', 'LA Selection Algorithm', 'la-selection-algorithm', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.last-protocol-suite', 'LAST Protocol Suite', 'last-protocol-suite', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.last-second-responder-nursing-competency', 'LAST Second Responder Nursing Competency', 'last-second-responder-nursing-competency', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.machine-cleaning-checklist', 'Machine Cleaning Checklist', 'machine-cleaning-checklist', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.medical-necessity-phrases', 'Medical Necessity Phrases', 'medical-necessity-phrases', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.mme-calculator-reference', 'MME Calculator Reference', 'mme-calculator-reference', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.nerve-block-patient-brochure', 'Nerve Block Patient Brochure', 'nerve-block-patient-brochure', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.out-of-plane-technique-sop', 'Out of Plane Technique SOP', 'out-of-plane-technique-sop', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.pacu-block-assessment-smart-template', 'PACU Block Assessment Smart Template', 'pacu-block-assessment-smart-template', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.pacu-los-tracker', 'PACU LOS Tracker', 'pacu-los-tracker', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.part-maneuver-guide', 'PART Maneuver Guide', 'part-maneuver-guide', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.patient-red-flag-card', 'Patient Red Flag Card', 'patient-red-flag-card', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.post-block-sensory-guide', 'Post Block Sensory Guide', 'post-block-sensory-guide', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.preop-nursing-smart-template', 'PreOp Nursing Smart Template', 'preop-nursing-smart-template', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.probe-cover-gel-management-standard', 'Probe Cover Gel Management Standard', 'probe-cover-gel-management-standard', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.probe-cover-selection-guide', 'Probe Cover Selection Guide', 'probe-cover-selection-guide', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.ra-consent-form', 'RA Consent Form', 'ra-consent-form', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.red-flag-recognition-card', 'Red Flag Recognition Card', 'red-flag-recognition-card', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.sedation-administration-monitoring-sop', 'Sedation Administration Monitoring SOP', 'sedation-administration-monitoring-sop', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.standardized-test-dose-protocol', 'Standardized Test Dose Protocol', 'standardized-test-dose-protocol', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.sterile-setup-assist-competency', 'Sterile Setup Assist Competency', 'sterile-setup-assist-competency', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.triangle-of-success-setup-guide', 'Triangle of Success Setup Guide', 'triangle-of-success-setup-guide', 'deliverable', 'foundation', 'block-ops'),
  ('foundation.weight-based-max-dose-calculator', 'Weight Based Max Dose Calculator', 'weight-based-max-dose-calculator', 'deliverable', 'foundation', 'block-ops')
on conflict (object_id) do update set
  title = excluded.title,
  slug = excluded.slug,
  object_type = excluded.object_type,
  package = excluded.package,
  owner = excluded.owner,
  updated_at = now();

-- 2. Seed representations
insert into content_representations (object_id, representation_type, knowledge_layer, audience, workspace_visibility, review_status, scope_type, site_id, agent_facing, version, source_path, storage_path) values
  ('foundation.adjuvant-dosing-guide', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Adjuvant_Dosing_Guide.md', 'foundation/Adjuvant_Dosing_Guide.md'),
  ('foundation.block-bay-workflow-logic', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Block_Bay_Workflow_Logic.md', 'foundation/Block_Bay_Workflow_Logic.md'),
  ('foundation.block-bay-workflow-logic', 'agent_document', 'layer2_agent', 'internal', 'internal_only', 'draft', 'global_standard', null, true, null, 'agent-knowledge/Block_Bay_Workflow_Logic.agent.md', 'agent-knowledge/Block_Bay_Workflow_Logic.agent.md'),
  ('foundation.block-cart-par-level-guide', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Block_Cart_Par_Level_Guide.md', 'foundation/Block_Cart_Par_Level_Guide.md'),
  ('foundation.block-cart-planogram', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Block_Cart_Planogram.md', 'foundation/Block_Cart_Planogram.md'),
  ('foundation.block-champion-charter', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Block_Champion_Charter.md', 'foundation/Block_Champion_Charter.md'),
  ('foundation.block-champion-charter', 'agent_document', 'layer2_agent', 'internal', 'internal_only', 'draft', 'global_standard', null, true, null, 'agent-knowledge/Block_Champion_Charter.agent.md', 'agent-knowledge/Block_Champion_Charter.agent.md'),
  ('foundation.block-lead-nurse-responsibility-list', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Block_Lead_Nurse_Responsibility_List.md', 'foundation/Block_Lead_Nurse_Responsibility_List.md'),
  ('foundation.block-lead-nurse-responsibility-list', 'agent_document', 'layer2_agent', 'internal', 'internal_only', 'draft', 'global_standard', null, true, null, 'agent-knowledge/Block_Lead_Nurse_Responsibility_List.agent.md', 'agent-knowledge/Block_Lead_Nurse_Responsibility_List.agent.md'),
  ('foundation.block-procedure-note-template', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Block_Procedure_Note_Template.md', 'foundation/Block_Procedure_Note_Template.md'),
  ('foundation.block-status-tracking-board-guide', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Block_Status_Tracking_Board_Guide.md', 'foundation/Block_Status_Tracking_Board_Guide.md'),
  ('foundation.block-success-failure-log', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Block_Success_Failure_Log.md', 'foundation/Block_Success_Failure_Log.md'),
  ('foundation.block-time-out-checklist', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Block_Time_Out_Checklist.md', 'foundation/Block_Time_Out_Checklist.md'),
  ('foundation.block-time-out-checklist', 'agent_document', 'layer2_agent', 'internal', 'internal_only', 'draft', 'global_standard', null, true, null, 'agent-knowledge/Block_Time_Out_Checklist.agent.md', 'agent-knowledge/Block_Time_Out_Checklist.agent.md'),
  ('foundation.breakthrough-pain-protocol', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Breakthrough_Pain_Protocol.md', 'foundation/Breakthrough_Pain_Protocol.md'),
  ('foundation.clean-vs-sterile-protocol', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Clean_vs_Sterile_Protocol.md', 'foundation/Clean_vs_Sterile_Protocol.md'),
  ('foundation.cpt-icd10-crosswalk', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/CPT_ICD10_Crosswalk.md', 'foundation/CPT_ICD10_Crosswalk.md'),
  ('foundation.daily-cart-restock-checklist', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Daily_Cart_Restock_Checklist.md', 'foundation/Daily_Cart_Restock_Checklist.md'),
  ('foundation.exparel-utilization-criteria', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Exparel_Utilization_Criteria.md', 'foundation/Exparel_Utilization_Criteria.md'),
  ('foundation.fall-prevention-patient-agreement', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Fall_Prevention_Patient_Agreement.md', 'foundation/Fall_Prevention_Patient_Agreement.md'),
  ('foundation.fall-risk-assessment', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Fall_Risk_Assessment.md', 'foundation/Fall_Risk_Assessment.md'),
  ('foundation.gel-management-sop', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Gel_Management_SOP.md', 'foundation/Gel_Management_SOP.md'),
  ('foundation.high-volume-dilution-chart', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/High_Volume_Dilution_Chart.md', 'foundation/High_Volume_Dilution_Chart.md'),
  ('foundation.high-volume-dilution-chart', 'agent_document', 'layer2_agent', 'internal', 'internal_only', 'draft', 'global_standard', null, true, null, 'agent-knowledge/High_Volume_Dilution_Chart.agent.md', 'agent-knowledge/High_Volume_Dilution_Chart.agent.md'),
  ('foundation.hydrodissection-opening-pressure-protocol', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Hydrodissection_Opening_Pressure_Protocol.md', 'foundation/Hydrodissection_Opening_Pressure_Protocol.md'),
  ('foundation.in-plane-technique-sop', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/In_Plane_Technique_SOP.md', 'foundation/In_Plane_Technique_SOP.md'),
  ('foundation.intraneural-injection-stop-criteria', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Intraneural_Injection_Stop_Criteria.md', 'foundation/Intraneural_Injection_Stop_Criteria.md'),
  ('foundation.knobology-cheat-sheet', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Knobology_Cheat_Sheet.md', 'foundation/Knobology_Cheat_Sheet.md'),
  ('foundation.la-selection-algorithm', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/LA_Selection_Algorithm.md', 'foundation/LA_Selection_Algorithm.md'),
  ('foundation.last-protocol-suite', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/LAST_Protocol_Suite.md', 'foundation/LAST_Protocol_Suite.md'),
  ('foundation.last-protocol-suite', 'agent_document', 'layer2_agent', 'internal', 'internal_only', 'draft', 'global_standard', null, true, null, 'agent-knowledge/LAST_Protocol_Suite.agent.md', 'agent-knowledge/LAST_Protocol_Suite.agent.md'),
  ('foundation.last-second-responder-nursing-competency', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/LAST_Second_Responder_Nursing_Competency.md', 'foundation/LAST_Second_Responder_Nursing_Competency.md'),
  ('foundation.last-second-responder-nursing-competency', 'agent_document', 'layer2_agent', 'internal', 'internal_only', 'draft', 'global_standard', null, true, null, 'agent-knowledge/LAST_Second_Responder_Nursing_Competency.agent.md', 'agent-knowledge/LAST_Second_Responder_Nursing_Competency.agent.md'),
  ('foundation.machine-cleaning-checklist', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Machine_Cleaning_Checklist.md', 'foundation/Machine_Cleaning_Checklist.md'),
  ('foundation.medical-necessity-phrases', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Medical_Necessity_Phrases.md', 'foundation/Medical_Necessity_Phrases.md'),
  ('foundation.mme-calculator-reference', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/MME_Calculator_Reference.md', 'foundation/MME_Calculator_Reference.md'),
  ('foundation.nerve-block-patient-brochure', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Nerve_Block_Patient_Brochure.md', 'foundation/Nerve_Block_Patient_Brochure.md'),
  ('foundation.out-of-plane-technique-sop', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Out_of_Plane_Technique_SOP.md', 'foundation/Out_of_Plane_Technique_SOP.md'),
  ('foundation.pacu-block-assessment-smart-template', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/PACU_Block_Assessment_Smart_Template.md', 'foundation/PACU_Block_Assessment_Smart_Template.md'),
  ('foundation.pacu-los-tracker', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/PACU_LOS_Tracker.md', 'foundation/PACU_LOS_Tracker.md'),
  ('foundation.part-maneuver-guide', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/PART_Maneuver_Guide.md', 'foundation/PART_Maneuver_Guide.md'),
  ('foundation.patient-red-flag-card', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Patient_Red_Flag_Card.md', 'foundation/Patient_Red_Flag_Card.md'),
  ('foundation.post-block-sensory-guide', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Post_Block_Sensory_Guide.md', 'foundation/Post_Block_Sensory_Guide.md'),
  ('foundation.preop-nursing-smart-template', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/PreOp_Nursing_Smart_Template.md', 'foundation/PreOp_Nursing_Smart_Template.md'),
  ('foundation.probe-cover-gel-management-standard', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Probe_Cover_Gel_Management_Standard.md', 'foundation/Probe_Cover_Gel_Management_Standard.md'),
  ('foundation.probe-cover-selection-guide', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Probe_Cover_Selection_Guide.md', 'foundation/Probe_Cover_Selection_Guide.md'),
  ('foundation.ra-consent-form', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/RA_Consent_Form.md', 'foundation/RA_Consent_Form.md'),
  ('foundation.red-flag-recognition-card', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Red_Flag_Recognition_Card.md', 'foundation/Red_Flag_Recognition_Card.md'),
  ('foundation.sedation-administration-monitoring-sop', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Sedation_Administration_Monitoring_SOP.md', 'foundation/Sedation_Administration_Monitoring_SOP.md'),
  ('foundation.standardized-test-dose-protocol', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Standardized_Test_Dose_Protocol.md', 'foundation/Standardized_Test_Dose_Protocol.md'),
  ('foundation.standardized-test-dose-protocol', 'agent_document', 'layer2_agent', 'internal', 'internal_only', 'draft', 'global_standard', null, true, null, 'agent-knowledge/Standardized_Test_Dose_Protocol.agent.md', 'agent-knowledge/Standardized_Test_Dose_Protocol.agent.md'),
  ('foundation.sterile-setup-assist-competency', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Sterile_Setup_Assist_Competency.md', 'foundation/Sterile_Setup_Assist_Competency.md'),
  ('foundation.triangle-of-success-setup-guide', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Triangle_of_Success_Setup_Guide.md', 'foundation/Triangle_of_Success_Setup_Guide.md'),
  ('foundation.weight-based-max-dose-calculator', 'human_document', 'layer1_human', 'client', 'client_visible', 'draft', 'global_standard', null, false, null, 'deliverables/foundation/Weight_Based_Max_Dose_Calculator.md', 'foundation/Weight_Based_Max_Dose_Calculator.md'),
  ('foundation.weight-based-max-dose-calculator', 'agent_document', 'layer2_agent', 'internal', 'internal_only', 'draft', 'global_standard', null, true, null, 'agent-knowledge/Weight_Based_Max_Dose_Calculator.agent.md', 'agent-knowledge/Weight_Based_Max_Dose_Calculator.agent.md')
on conflict (source_path) do update set
  object_id = excluded.object_id,
  representation_type = excluded.representation_type,
  knowledge_layer = excluded.knowledge_layer,
  audience = excluded.audience,
  workspace_visibility = excluded.workspace_visibility,
  review_status = excluded.review_status,
  scope_type = excluded.scope_type,
  site_id = excluded.site_id,
  agent_facing = excluded.agent_facing,
  version = excluded.version,
  storage_path = excluded.storage_path,
  updated_at = now();

-- 3. Summary checks
-- Expected after seed: 46 human foundation representations + 9 agent representations = 55 representations
-- Expected canonical objects: 46 total foundation objects (9 of them have both human + agent representations)

commit;
