const makeTask = ({ taskKey, title, description, owner, workstream, milestoneSlug, sortOrder, compliance = false, legal = false }) => ({
  taskKey,
  title,
  description,
  primaryOwner: owner,
  status: 'locked',
  priority: 'medium',
  workstream,
  milestoneSlug,
  complianceFlag: compliance,
  legalGateFlag: legal,
  changedByNewInfo: true,
  sortOrder,
});

const patientWorkstream = 'Future Product — Patient Education & Experience';
const payerWorkstream = 'Future Product — Payer Intelligence & Integration';

export const FUTURE_PRODUCT_TASKS = [
  makeTask({ taskKey: 'M4-PAT-001', title: 'Define patient-education outcomes and pre-op workflow', description: 'Map intended patient/facility outcomes, waiting-period touchpoints, staff ownership, question handoff, and explicit non-clinical boundaries.', owner: 'Samir', workstream: patientWorkstream, milestoneSlug: 'm4-validation-closed', sortOrder: 1101, compliance: true }),
  makeTask({ taskKey: 'M4-PAT-002', title: 'Define approved patient content and review pathway', description: 'Create the content inventory and exact clinical, legal, compliance, client, version, and release-review requirements.', owner: 'Samir', workstream: patientWorkstream, milestoneSlug: 'm4-validation-closed', sortOrder: 1102, compliance: true, legal: true }),
  makeTask({ taskKey: 'M4-PAT-003', title: 'Select tablet, kiosk, QR, or mobile delivery model', description: 'Compare workflow fit, cost, device burden, accessibility, privacy, support, and adoption before selecting the patient-facing surface.', owner: 'Max', workstream: patientWorkstream, milestoneSlug: 'm4-validation-closed', sortOrder: 1103 }),
  makeTask({ taskKey: 'M4-PAT-004', title: 'Define accessibility, language, and health-literacy standards', description: 'Set requirements for language quality, captions/audio, visual accessibility, reading level, accommodations, and testing.', owner: 'Bloq', workstream: patientWorkstream, milestoneSlug: 'm4-validation-closed', sortOrder: 1104, compliance: true }),
  makeTask({ taskKey: 'M4-PAT-005', title: 'Define patient privacy, consent, PHI, and retention controls', description: 'Minimize data collection and define authorization, identity, PHI, survey, retention, deletion, tenant, and aggregate-reporting controls.', owner: 'Samir', workstream: patientWorkstream, milestoneSlug: 'm4-validation-closed', sortOrder: 1105, compliance: true, legal: true }),
  makeTask({ taskKey: 'M4-PAT-006', title: 'Define patient survey and KPI dictionary', description: 'Define the short survey, completion/understanding/preparedness/satisfaction measures, bias limitations, owners, sources, and approved interpretation.', owner: 'Samir', workstream: patientWorkstream, milestoneSlug: 'm4-validation-closed', sortOrder: 1106, compliance: true }),
  makeTask({ taskKey: 'M4-PAT-007', title: 'Build the isolated patient-facing education experience', description: 'Build the approved patient flow separately from the facility Dashboard with controlled content, safe exits, and staff-question escalation.', owner: 'Max', workstream: patientWorkstream, milestoneSlug: 'm4-validation-closed', sortOrder: 1107, compliance: true }),
  makeTask({ taskKey: 'M4-PAT-008', title: 'Build site configuration and approved aggregate Dashboard reporting', description: 'Add site-approved content configuration, exact-version controls, permitted aggregate survey intake, KPI states, and no cross-tenant exposure.', owner: 'Max', workstream: patientWorkstream, milestoneSlug: 'm4-validation-closed', sortOrder: 1108, compliance: true }),
  makeTask({ taskKey: 'M4-PAT-009', title: 'Define tablet security, MDM, cleaning, charging, and loss procedures', description: 'Create the physical/device operating standard including kiosk mode, updates, resets, infection control, storage, charging, inventory, loss, and support.', owner: 'Max', workstream: patientWorkstream, milestoneSlug: 'm4-validation-closed', sortOrder: 1109, compliance: true }),
  makeTask({ taskKey: 'M4-PAT-010', title: 'Run patient-experience usability, workflow, accessibility, privacy, and security tests', description: 'Test the complete experience with approved reviewers and resolve critical content, workflow, accessibility, privacy, and security defects.', owner: 'Bloq', workstream: patientWorkstream, milestoneSlug: 'm4-validation-closed', sortOrder: 1110, compliance: true, legal: true }),
  makeTask({ taskKey: 'M4-PAT-011', title: 'Pilot the patient education experience with an approved foundational client', description: 'Run a controlled site pilot only after all review gates pass; record adoption, workflow impact, approved survey results, incidents, and limitations.', owner: 'Samir', workstream: patientWorkstream, milestoneSlug: 'm4-validation-closed', sortOrder: 1111, compliance: true, legal: true }),
  makeTask({ taskKey: 'M4-PAT-012', title: 'Complete patient-platform evidence review and scale decision', description: 'Analyze the pilot without overstating causality and decide to scale, revise, pause, or stop with owners and evidence.', owner: 'Samir', workstream: patientWorkstream, milestoneSlug: 'm4-validation-closed', sortOrder: 1112, compliance: true }),

  makeTask({ taskKey: 'M5-PAY-001', title: 'Define payer-intelligence scope and regulated-advice boundaries', description: 'Separate source-linked documentation guidance from patient-specific advice, coding decisions, coverage determinations, and reimbursement promises.', owner: 'Samir', workstream: payerWorkstream, milestoneSlug: 'm5-founding-partner-ready', sortOrder: 1201, compliance: true, legal: true }),
  makeTask({ taskKey: 'M5-PAY-002', title: 'Define canonical payer-policy and applicability data model', description: 'Model payer, plan, policy, procedure/context, site of service, geography, effective dates, requirements, source, review state, supersession, and uncertainty.', owner: 'Max', workstream: payerWorkstream, milestoneSlug: 'm5-founding-partner-ready', sortOrder: 1202, compliance: true }),
  makeTask({ taskKey: 'M5-PAY-003', title: 'Define payer primary-source hierarchy and governance', description: 'Define acceptable sources, provenance, qualified reviewers, review cadence, conflict handling, stale-policy behavior, and retirement rules.', owner: 'Samir', workstream: payerWorkstream, milestoneSlug: 'm5-founding-partner-ready', sortOrder: 1203, compliance: true, legal: true }),
  makeTask({ taskKey: 'M5-PAY-004', title: 'Select initial payer, site, and jurisdiction cohort', description: 'Select a narrow commercially relevant cohort based on client mix, data availability, complexity, update burden, and validation access.', owner: 'Adrian', workstream: payerWorkstream, milestoneSlug: 'm5-founding-partner-ready', sortOrder: 1204 }),
  makeTask({ taskKey: 'M5-PAY-005', title: 'Acquire, normalize, version, and review initial payer policies', description: 'Build the initial governed corpus with policy identifiers, primary-source links, effective dates, applicability limits, extracted requirements, and reviewer state.', owner: 'Bloq', workstream: payerWorkstream, milestoneSlug: 'm5-founding-partner-ready', sortOrder: 1205, compliance: true, legal: true }),
  makeTask({ taskKey: 'M5-PAY-006', title: 'Map payer requirements to documentation guidance', description: 'Translate reviewed requirements into source-linked guidance and workflow checks while preserving uncertainty and human-review gates.', owner: 'Samir', workstream: payerWorkstream, milestoneSlug: 'm5-founding-partner-ready', sortOrder: 1206, compliance: true, legal: true }),
  makeTask({ taskKey: 'M5-PAY-007', title: 'Build client, site, payer, and plan configuration controls', description: 'Implement tenant-safe configuration so guidance reflects approved client context without mutating the universal payer-policy baseline.', owner: 'Max', workstream: payerWorkstream, milestoneSlug: 'm5-founding-partner-ready', sortOrder: 1207, compliance: true }),
  makeTask({ taskKey: 'M5-PAY-008', title: 'Build policy-change monitoring, versioning, alerts, and fail-closed behavior', description: 'Detect source changes, route review, preserve prior versions, alert affected clients after approval, and withhold guidance when currency cannot be verified.', owner: 'Max', workstream: payerWorkstream, milestoneSlug: 'm5-founding-partner-ready', sortOrder: 1208, compliance: true }),
  makeTask({ taskKey: 'M5-PAY-009', title: 'Build source-linked payer guidance in the Dashboard', description: 'Present applicable governed guidance, sources, dates, limitations, review status, uncertainty, and escalation without guaranteeing coverage or payment.', owner: 'Max', workstream: payerWorkstream, milestoneSlug: 'm5-founding-partner-ready', sortOrder: 1209, compliance: true, legal: true }),
  makeTask({ taskKey: 'M5-PAY-010', title: 'Validate payer guidance accuracy and operating controls', description: 'Compare outputs with qualified review and available real-world evidence; test stale data, conflicts, wrong-context denial, tenant isolation, auditability, and escalation.', owner: 'Bloq', workstream: payerWorkstream, milestoneSlug: 'm5-founding-partner-ready', sortOrder: 1210, compliance: true, legal: true }),
  makeTask({ taskKey: 'M5-PAY-011', title: 'Assess direct payer and clearinghouse integration feasibility', description: 'Evaluate interfaces, contracts, BAAs, privacy/security, data rights, maintenance, unit economics, and practical value before approving any integration.', owner: 'Max', workstream: payerWorkstream, milestoneSlug: 'm5-founding-partner-ready', sortOrder: 1211, compliance: true, legal: true }),
  makeTask({ taskKey: 'M5-PAY-012', title: 'Pilot one approved payer integration and decide commercialization', description: 'After the rule-library foundation and all gates pass, test one approved integration, verify accuracy/reliability, and decide scale, revision, pause, or stop.', owner: 'Samir', workstream: payerWorkstream, milestoneSlug: 'm5-founding-partner-ready', sortOrder: 1212, compliance: true, legal: true }),
];

export const FUTURE_PRODUCT_DEPENDENCIES = [
  ['M4-PAT-002', 'M4-PAT-001'], ['M4-PAT-003', 'M4-PAT-001'], ['M4-PAT-004', 'M4-PAT-001'], ['M4-PAT-005', 'M4-PAT-001'], ['M4-PAT-006', 'M4-PAT-001'],
  ['M4-PAT-007', 'M4-PAT-002'], ['M4-PAT-007', 'M4-PAT-003'], ['M4-PAT-007', 'M4-PAT-004'], ['M4-PAT-007', 'M4-PAT-005'],
  ['M4-PAT-008', 'M4-PAT-005'], ['M4-PAT-008', 'M4-PAT-006'], ['M4-PAT-008', 'M4-PAT-007'], ['M4-PAT-009', 'M4-PAT-003'],
  ['M4-PAT-010', 'M4-PAT-007'], ['M4-PAT-010', 'M4-PAT-008'], ['M4-PAT-010', 'M4-PAT-009'], ['M4-PAT-011', 'M4-PAT-010'], ['M4-PAT-012', 'M4-PAT-011'],
  ['M5-PAY-002', 'M5-PAY-001'], ['M5-PAY-003', 'M5-PAY-001'], ['M5-PAY-004', 'M5-PAY-001'], ['M5-PAY-005', 'M5-PAY-002'], ['M5-PAY-005', 'M5-PAY-003'], ['M5-PAY-005', 'M5-PAY-004'],
  ['M5-PAY-006', 'M5-PAY-005'], ['M5-PAY-007', 'M5-PAY-002'], ['M5-PAY-007', 'M5-PAY-006'], ['M5-PAY-008', 'M5-PAY-005'], ['M5-PAY-009', 'M5-PAY-007'], ['M5-PAY-009', 'M5-PAY-008'],
  ['M5-PAY-010', 'M5-PAY-009'], ['M5-PAY-011', 'M5-PAY-010'], ['M5-PAY-012', 'M5-PAY-011'],
].map(([taskKey, dependsOnTaskKey]) => ({ taskKey, dependsOnTaskKey, dependencyType: 'finish_to_start' }));
