const task = ({
  taskKey,
  title,
  description,
  primaryOwner,
  milestoneSlug,
  workstream,
  sortOrder,
  complianceFlag = false,
  legalGateFlag = false,
}) => ({
  taskKey,
  title,
  description,
  primaryOwner,
  status: taskKey.startsWith('M1-') ? 'ready' : 'locked',
  priority: 'critical',
  workstream,
  milestoneSlug,
  complianceFlag,
  legalGateFlag,
  changedByNewInfo: true,
  sortOrder,
});

export const MILESTONE_BOUNDARY_TASKS = [
  task({
    taskKey: 'M1-PAY-01',
    title: 'Define mock payment-status record and gate',
    description: 'Define M1 mock-only payment fields and states for Contract & Signature through Client Kickoff: proposal amount/schedule, billing contact when known, trigger, due state, simulated received/waived/blocked state, evidence, exception owner, and downstream authorization. Do not build or claim real invoicing, collection, accounting, or payment operations.',
    primaryOwner: 'Samir',
    milestoneSlug: 'm1-mock-run-build-ready',
    workstream: 'Contract Signed to Onboarding Handoff',
    sortOrder: 1105,
    legalGateFlag: true,
  }),
  task({
    taskKey: 'M1-PAY-02',
    title: 'Test mock payment-dependent Client Kickoff gate',
    description: 'Record a simulated payment state and prove mock Client Kickoff/onboarding advances only when the configured condition is satisfied or an authorized mock exception is recorded. Confirm no real charge, invoice, receipt, or payment processing occurs.',
    primaryOwner: 'Bloq',
    milestoneSlug: 'm1-mock-run-build-ready',
    workstream: 'Contract Signed to Onboarding Handoff',
    sortOrder: 1107,
    legalGateFlag: true,
  }),
  task({
    taskKey: 'M2-OPS-01',
    title: 'Finalize site-readiness and accountable-role intake',
    description: 'Finalize the real-client packet for safety infrastructure and emergency resources, equipment/supplies, workflow, clinical and operational owners, staffing/coverage, stakeholder roles, evidence, qualified approvals, exceptions, and explicit go-live blockers.',
    primaryOwner: 'Samir',
    milestoneSlug: 'm2-mock-run-complete',
    workstream: 'Foundational Client Operating Readiness',
    sortOrder: 161,
    complianceFlag: true,
    legalGateFlag: true,
  }),
  task({
    taskKey: 'M2-OPS-02',
    title: 'Finalize buying, procurement, and vendor-onboarding path',
    description: 'Define the healthcare-client buying path from budget authority through procurement/legal review, vendor registration, PO and accounts-payable requirements, signature authority, buying-stage status, owners, lead times, blockers, and physical equipment/supply purchasing where applicable.',
    primaryOwner: 'Adrian',
    milestoneSlug: 'm2-mock-run-complete',
    workstream: 'Foundational Client Operating Readiness',
    sortOrder: 162,
    complianceFlag: true,
    legalGateFlag: true,
  }),
  task({
    taskKey: 'M2-OPS-03',
    title: 'Implement operating-readiness records and gates',
    description: 'Implement site-scoped, versioned records and audit history for readiness evidence, accountable roles, procurement/buying status, agreement and payment conditions, approvals, unresolved exceptions, and fail-closed training/go-live authorization.',
    primaryOwner: 'Max',
    milestoneSlug: 'm2-mock-run-complete',
    workstream: 'Foundational Client Operating Readiness',
    sortOrder: 163,
    complianceFlag: true,
    legalGateFlag: true,
  }),
  task({
    taskKey: 'M2-OPS-04',
    title: 'Verify operating-readiness pathways with mock records',
    description: 'Use M2 mock-client and site records to test site readiness, role/staffing intake, procurement, agreement, billing/payment, training, go-live/no-go, and support pathways, including missing-input, rejection, rework, exception, and blocked-advance cases.',
    primaryOwner: 'Bloq',
    milestoneSlug: 'm2-mock-run-complete',
    workstream: 'Foundational Client Operating Readiness',
    sortOrder: 164,
    complianceFlag: true,
    legalGateFlag: true,
  }),
  task({
    taskKey: 'M3-EXEC-01',
    title: 'Conduct the external attending review and test',
    description: 'Run the approved review protocol with the required outside attending anesthesiologists, capture attendance and exact findings, test clinically relevant safety and operating assumptions, and record whether the system passed, failed, or requires remediation.',
    primaryOwner: 'Samir',
    milestoneSlug: 'm3-trusted-anesthesiologist-validation',
    workstream: 'External Validation Session',
    sortOrder: 145,
    complianceFlag: true,
  }),
  task({
    taskKey: 'M5-01',
    title: 'Confirm paid-client agreement and payment authorization',
    description: 'Verify an executed paid-client agreement, approved scope and pricing, payer/accounts-payable details, and the required initial payment received or contractual payment trigger satisfied before provisioning begins.',
    primaryOwner: 'Adrian',
    milestoneSlug: 'm5-founding-partner-ready',
    workstream: 'Paid Client Onboarding',
    sortOrder: 10,
    complianceFlag: true,
    legalGateFlag: true,
  }),
  task({
    taskKey: 'M5-02',
    title: 'Complete paid-client readiness and provisioning',
    description: 'Apply the approved site, staffing, procurement, security, portal/data, content, training, and support readiness gates to the paid client; provision only after required approvals and blockers are clear.',
    primaryOwner: 'Bloq',
    milestoneSlug: 'm5-founding-partner-ready',
    workstream: 'Paid Client Onboarding',
    sortOrder: 20,
    complianceFlag: true,
  }),
  task({
    taskKey: 'M5-03',
    title: 'Complete paid-client kickoff and onboarding',
    description: 'Run kickoff, confirm accountable contacts and responsibilities, deliver approved onboarding materials and access, schedule training and implementation, and record client acknowledgment and unresolved actions.',
    primaryOwner: 'Adrian',
    milestoneSlug: 'm5-founding-partner-ready',
    workstream: 'Paid Client Onboarding',
    sortOrder: 30,
  }),
  task({
    taskKey: 'M5-04',
    title: 'Verify paid-client operations and support started',
    description: 'Verify approved delivery surfaces, initial operating cadence and KPI baseline, support/escalation, and ownership/disposition of early issues.',
    primaryOwner: 'Bloq',
    milestoneSlug: 'm5-founding-partner-ready',
    workstream: 'Paid Client Onboarding',
    sortOrder: 40,
    complianceFlag: true,
  }),
  task({
    taskKey: 'M5-05',
    title: 'Approve paid-client onboarding completion',
    description: 'Close M5 only when agreement/payment authorization, readiness, provisioning, kickoff, access, support, and accountable client acceptance evidence are complete and real delivery is underway.',
    primaryOwner: 'Adrian',
    milestoneSlug: 'm5-founding-partner-ready',
    workstream: 'Paid Client Onboarding',
    sortOrder: 50,
    complianceFlag: true,
    legalGateFlag: true,
  }),
];

const dependency = (taskKey, dependsOnTaskKey, dependencyType = 'finish_to_start') => ({
  taskKey,
  dependsOnTaskKey,
  dependencyType,
});

export const CANONICAL_MILESTONE_DEPENDENCIES = [
  ['m2-mock-run-complete', 'm1-mock-run-build-ready'],
  ['m3-trusted-anesthesiologist-validation', 'm2-mock-run-complete'],
  ['m4-validation-closed', 'm3-trusted-anesthesiologist-validation'],
  ['m5-founding-partner-ready', 'm4-validation-closed'],
].map(([milestoneSlug, dependsOnMilestoneSlug]) => ({ milestoneSlug, dependsOnMilestoneSlug }));

export const MILESTONE_BOUNDARY_DEPENDENCIES = [
  dependency('M1-PAY-02', 'M1-PAY-01'),
  dependency('M1-104', 'M1-PAY-02'),
  dependency('M1-PAY-02', 'M1-125'),
  dependency('M1-104', 'M1-100'),
  dependency('M1-169', 'M1-161'),
  dependency('M1-169', 'M1-GR-023'),
  dependency('M1-169', 'M1-GR-024'),
  dependency('M1-169', 'M1-165'),
  dependency('M1-169', 'M1-168'),
  dependency('M1-182', 'M1-169'),
  dependency('M1-183', 'M1-182'),
  dependency('M2-OPS-03', 'M2-OPS-01'),
  dependency('M2-OPS-03', 'M2-OPS-02'),
  dependency('M2-OPS-03', 'M2-09'),
  dependency('M2-OPS-04', 'M2-OPS-03'),
  dependency('M2-OPS-04', 'M2-08'),
  dependency('M2-OPS-04', 'M2-15'),
  ...['M2-OPS-04', 'M2-06', 'M2-07', 'M2-10', 'M2-14', 'M2-LGL-011', 'M2-FND-023', 'M2-ROI-087']
    .map((dependsOnTaskKey) => dependency('M2-16', dependsOnTaskKey, 'gate')),
  ...['M3-11', 'M3-12', 'M3-13', 'M3-14']
    .map((dependsOnTaskKey) => dependency('M3-EXEC-01', dependsOnTaskKey)),
  dependency('M3-EXEC-01', 'M2-16', 'gate'),
  dependency('M3-15', 'M3-EXEC-01'),
  dependency('M4-01', 'M3-16', 'gate'),
  dependency('M5-01', 'M4-05', 'gate'),
  dependency('M5-02', 'M5-01'),
  dependency('M5-03', 'M5-02'),
  dependency('M5-04', 'M5-03'),
  dependency('M5-05', 'M5-04'),
  ...['M2-LGL-001', 'M2-LGL-002', 'M2-LGL-003', 'M2-LGL-004', 'M2-LGL-005', 'M2-LGL-006', 'M2-LGL-007', 'M2-LGL-008', 'M2-LGL-080']
    .map((dependsOnTaskKey) => dependency('M2-LGL-009', dependsOnTaskKey)),
  dependency('M2-LGL-010', 'M2-LGL-009'),
  dependency('M2-LGL-102', 'M2-LGL-010'),
  dependency('M2-LGL-011', 'M2-LGL-102'),
];
